version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic-stack_network
    restart: unless-stopped
    
  kibana:
    image: kibana:8.5.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic-stack_network
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic-stack_network:
    driver: bridge